name: Run Action for Any Branch with Conditions

on:
  push: 
    branches:
      - '*'  # Matches all branches

jobs:
  handle-master:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: github.ref == 'refs/heads/master'  # Run only for the master branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Master branch script
        run: echo "Running job for master branch."

  handle-deploy:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: github.ref == 'refs/heads/deploy'  # Run only for the deploy branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy branch script
        run: echo "Running job for deploy branch."

  handle-feature:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: github.ref == 'refs/heads/feature'  # Run only for the feature branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Feature branch script
        run: echo "Running job for feature branch."

  handle-other-branches:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: |
      startsWith(github.ref, 'refs/heads/') && 
      github.ref != 'refs/heads/master' && 
      github.ref != 'refs/heads/deploy' && 
      github.ref != 'refs/heads/feature'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generic script for other branches
        run: echo "Running job for other branches."
