name: Conditional Build & Branch Handling

on:
  push: 
    branches:
      - '*'  # Trigger the workflow for all branches

jobs:
  handle-master:
    runs-on: [self-hosted, self-github]  # Use the self-hosted runner
    if: github.ref == 'refs/heads/master'  # Only run for the master branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Master branch script
        run: echo "Running job for master branch."

  handle-deploy:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: github.ref == 'refs/heads/deploy'  # Run only for the deploy branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy branch script
        run: echo "Running job for deploy branch."

  handle-feature:
    runs-on: [self-hosted, self-github]  # Specify runner by label
    if: github.ref == 'refs/heads/feature'  # Run only for the feature branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build JAR/WAR file
        run: |
          ./gradlew clean build  # Adjust this with your build script or logic

      - name: Upload JAR/WAR as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: build/libs/*.jar  # Path to your built JAR/WAR

  handle-other-branches:
    runs-on: [self-hosted, self-github]
    if: |
      startsWith(github.ref, 'refs/heads/') && 
      github.ref != 'refs/heads/master' && 
      github.ref != 'refs/heads/deploy' && 
      github.ref != 'refs/heads/feature'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Other branches script
        run: echo "Running job for other branches."
